import { StepFormContextProvider } from '@/context/StepFormContext'
import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { SizingContextProvider } from '@/context/IrradianceContext'

const roboto = Roboto({ weight: ['500', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dimensiona AI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <SizingContextProvider>
          <StepFormContextProvider>
            {children}
          </StepFormContextProvider>
        </SizingContextProvider>
      </body>
    </html>
  )
}
